spending_limit_interval: 'yearly'
base_funding_amt: 150
refill_trigger_percent: 0.75
refill_amts: []
approved_postal_codes:
  - 98222
  - 98243
  - 98245
  - 98250
  - 98261
  - 98279
  - 98280
  - 98286
  - 98297
approved_vendors:
  "ORCAS FOOD COOP": 98245
  "SAN JUAN ISLAND FOOD": 98250
  "San Juan Islands Food Hub": 98250
  "AURORA FARMS": 98250
  "BARN OWL BAKERY": 98261
  "BUCK BAY SHELLFISH": 98279
  "JOON FARM": 98250
  "KARI'S ISLAND ELIXIRS": 98250
  "LOPEZ VILLAGE FARM": 98261
  "LUM FARM": 98245
  "MAMA BIRD": 98250
  "MORNING STAR": 98280
  "NOOTKA\\s*ROSE": 98245
  "NORTH BEACH MUSHROOMS": 98245
  "NORTH STAR FARM": 98261
  "ROCHE HARBOR FARM": 98250
  "STONECREST FARM": 98261
  # "SUNNYFIELD FARM": 98261
  "SUNNYFIELD FAR": 10014   # there venmo version; if the zip doesn't match, it will match the approved postal codes
  "URSA MINOR": 98261
  "WATMOUGH BAY FARM": 98261
  "WEST\\s*BEACH": 98245
  "WOW FARM": 98279
  "TERRA FLEURS": 98122
  "WARM VALLEY ORCHAR": 98280
  "WARM VALLEY FARM": 98280
  "ORCAS FARM": 98245
  "NEW HANNAH FARM": 98250
  "GIRL MEETS DIRT": 98250
  "SAN JUAN ISLAND SE": 98250
  "SANJUANSEASALT": 98250

sms_declined_vendor_not_found_submsg: >
  'VENDOR_NAME' is not a verified Island Grown Card vendor.
sms_declined_over_balance_submsg: >
  'VENDOR_NAME' for $AUTH_AMT is over your current balance of $CURRENT_BALANCE
sms_declined_msg: >
  Island Grown Card:
    Your recent transaction was denied

  DECLINED_MSG

  reply STOP to unsubscribe
sms_balance_msg: >
  Island Grown Card:
    Current Balance: $CURRENT_BALANCE
    Spending Limit: $SPEND_LIMIT

  reply STOP to unsubscribe
sms_help_msg: >
  Island Grown Card:
   * reply B or BALANCE to see balance
   * reply V or VENDORS to see where you can use your card
   * reply H or HELP to see this message again.

  If your transaction is declined, you'll receive a message as to why.


  reply STOP to unsubscribe
sms_welcome_msg: >
  Welcome to your Island Grown Card!


  You can:
   * reply B or BALANCE to see your remaining balance
   * reply V or VENDORS to see where you can use your card
   * reply H or HELP to see this message again.
   * reply STOP to unsubscribe

  If your transaction is declined, you'll receive a message as to why.


  Thank you and enjoy your Island Grown Card!
sms_stop_msg: >
  Island Grown Card:

  We'll stop sending you notifications, including about declined transactions.

  To start receiving notifications again, just reply with anything.
sms_vendors_msg: >
  Island Grown Card Vendors:


  * San Juan Islands Food Hub
     www.sjifh.com

  Lopez Island
   * Barn Owl Bakery
   * Lopez Village Farm
   * Stonecrest Farm
   * Sunnyfield Farm
   * Watmough Bay Farm

  Orcas Island
   * Buck Bay Shellfish Farm
   * Girl Meets Dirt
   * Lum Farm
   * Morningstar Farm
   * Orcas Co-Op
   * Warm Valley Farm
   * West Beach Farm
   * Wise Owl Wellness (WOW) Farm

  San Juan Island
   * Aurora Farm
   * Joon Farm
   * Kari's Island Elixirs
   * Mama Bird Farm
   * New Hannah Farm
   * San Juan Co-Op
   * San Juan Sea Salt
   * Snowberry Farm
   * Sweet Earth Farm

  Waldron Island
   * Nootka Rose Farm

  reply STOP to unsubscribe
