spending_limit_interval: 'all_time'
base_funding_amt: 150
refill_trigger_percent: 0.75
refill_amts:
  - 75
  - 50
approved_postal_codes:
  - 98222
  - 98243
  - 98245
  - 98250
  - 98261
  - 98279
  - 98280
  - 98286
  - 98297
approved_vendors:
  "ORCAS FOOD COOP": 98245
  "SAN JUAN ISLAND FOOD": 98250
  "San Juan Islands Food Hub": 98250
  "SQ *AURORA FARMS": 98250
  "SQ *BARN OWL BAKERY": 98261
  "BARN OWL BAKERY INC": 98261
  "SQ *BUCK BAY SHELLFISH": 98279
  "SQ *GIRL MEETS DIRT": 98245
  "SQ *JOON FARM": 98250
  "SQ *KARI'S ISLAND ELIXIRS": 98250
  "SQ *LOPEZ VILLAGE FARM": 98261
  "SQ *LUM FARM LLC": 98245
  "SQ *MAMA BIRD FARM": 98250
  "SQ *MORNING STAR FARM": 98280
  "SQ *NOOTKA ROSE FARM": 98245
  "SQ *NORTH BEACH MUSHROOMS": 98245
  "SQ *NORTH STAR FARM FA": 98261
  "SQ *ROCHE HARBOR FARM": 98250
  "SQ *SAN JUAN ISLAND SE": 98250
  "SQ *STONECREST FARM &": 98261
  "SQ *SUNNYFIELD FARM": 98261
  "SQ *URSA MINOR": 98261
  "SQ *WATMOUGH BAY FARM": 98261
  "SQ *WESTBEACH FARM": 98245
  "SQ *WOW FARM LLC": 98279
  "TERRA FLEURS": 98122
