spending_limit_interval: 'yearly'
base_funding_amt: 150
refill_trigger_percent: 0.75
refill_amts: []
approved_postal_codes:
  - 98222
  - 98243
  - 98245
  - 98250
  - 98261
  - 98279
  - 98280
  - 98286
  - 98297
approved_vendors:
  "ORCAS FOOD COOP": 98245
  "SAN JUAN ISLAND FOOD": 98250
  "San Juan Islands Food Hub": 98250
  "SQ *AURORA FARMS": 98250
  "SQ *BARN OWL BAKERY": 98261
  "BARN OWL BAKERY INC": 98261
  "SQ *BUCK BAY SHELLFISH": 98279
  "SQ *JOON FARM": 98250
  "SQ *KARI'S ISLAND ELIXIRS": 98250
  "SQ *LOPEZ VILLAGE FARM": 98261
  "SQ *LUM FARM LLC": 98245
  "SQ *MAMA BIRD FARM": 98250
  "SQ *MORNING STAR FARM": 98280
  "SQ *NOOTKA ROSE FARM": 98245
  "SQ *NORTH BEACH MUSHROOMS": 98245
  "SQ *NORTH STAR FARM FA": 98261
  "SQ *ROCHE HARBOR FARM": 98250
  "SQ *STONECREST FARM &": 98261
  "SQ *SUNNYFIELD FARM": 98261
  "VENMO  *SUNNYFIELD FAR": 10014
  "SQ *URSA MINOR": 98261
  "SQ *WATMOUGH BAY FARM": 98261
  "SQ *WESTBEACH FARM": 98245
  "SQ *WEST BEACH FARM": 98245
  "SQ *WEST BEACH PRODUCE": 98245
  "SQ *WOW FARM LLC": 98279
  "TERRA FLEURS": 98122
  "SQ *WARM VALLEY ORCHAR": 98280
  "SQ *ORCAS FARM": 98245
  "SQ *NEW HANNAH FARM": 98250
  "SQ *GIRL MEETS DIRT": 98245
  "SP GIRL MEETS DIRT": 98245
  "SQ *SAN JUAN ISLAND SE": 98250
  "SP SANJUANSEASALT": 98250

sms_declined_vendor_not_found_submsg: >
  'VENDOR_NAME' is not a verified Island Grown Card vendor.
sms_declined_over_balance_submsg: >
  'VENDOR_NAME' for $AUTH_AMT is over your current balance of $CURRENT_BALANCE
sms_declined_msg: >
  Island Grown Card:
    Your recent transaction was denied

  DECLINED_MSG

  reply STOP to unsubscribe
sms_balance_msg: >
  Island Grown Card:
    Current Balance: $CURRENT_BALANCE
    Spending Limit: $SPEND_LIMIT

  reply STOP to unsubscribe
sms_help_msg: >
  Island Grown Card:
    reply B or BALANCE to see balance
    reply H or HELP to see this message again.

  If your transaction is declined, you'll receive a message as to why.

  reply STOP to unsubscribe
sms_welcome_msg: >
  Welcome to your Island Grown Card!

  You can:
    - reply B or BALANCE to see your remaining balance
    - reply H or HELP to see this message again.
    - reply STOP to unsubscribe

  If your transaction is declined, you'll receive a message as to why.


  Thank you and enjoy your Island Grown Card!
sms_stop_msg: >
  Island Grown Card:

  We'll stop sending you notifications, including about declined transactions.

  To start receiving notifications again, just reply with anything.
