---
name: Cardholder refill check
on:
  schedule:
    # Customize schedule expression at crontab.guru
    # currently running at 9am UTC
    - cron: "0 9 * * *"
  workflow_dispatch:
    #  allow manual updating

jobs:
  refill_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          check-latest: true
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: primary run
        run: yarn exec scripts/update_cardholder_spending_refills.js -f
        env:
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_WRITE_CARDHOLDER_KEY }}
